[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chrispfae-diffusion2D"
description = "Solving the 2D diffusion equation over square domain with FEM."
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.10"
keywords = ["diffusion_equation", "Solver", "FEM"]
license = {text = "BSD License"}
dependencies = ["numpy >= 1.23.4", "matplotlib >= 3.6.1; python_version < '3.11'"]
author = "chrispfae"
author_email = "christian.pfaendner@simtech.uni-stuttgart.de"
